id: P008013
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6091
  title: དེང་རབས་བོད་སྨན་ཆུ་ཁབ་
  author: ''
  volumes:
    a7cd36a6b8f04ef589bd156328cf4fd0:
      image_group_id: I1KG6283
      title: ''
      volume_number: 1
      total_pages: 118
ebook_metadata:
  title: དེང་རབས་བོད་སྨན་ཆུ་ཁབ་
  author: ''
  sku: P008013
  cover: cover.jpg
  layers:
  - pagination
