id: P008013
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:55:24.594795
source_metadata:
  id: bdr:W1KG6091
  title: དེང་རབས་བོད་སྨན་ཆུ་ཁབ་
  author: ''
  volumes:
    0928ab846e024523afe75fb65ede7cf8:
      image_group_id: I1KG6283
      title: Volume 1 of deng rabs bod sman chu khab
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
